---
title: "report.Rmd"
author: "Willy Müller"
date: "2023-02-27"
output: html_document
---


#ReportExercise_3.5_Aufgabe_2
#Datensatz einlesen und formatieren
```{r}
data <- read.csv("C:/Users/Admin/Desktop/AGDS/1249534s1-s6.csv",header=TRUE,na.strings=c(NA,'-'),sep=';')
```
#Select columns from the data
```{r}
log_response_data <- data |>
  dplyr::select(Experiment, increased_CO2, ambient_CO2, Time_.years.)
```
#Calculate the mean of the logarithm of the ratio between "increased CO2" and "ambient CO2". 
```{r}
log_response_per_experiment <- log_response_data |> 
  dplyr::group_by(Experiment)|>
  dplyr::summarise(mean = mean(log(increased_CO2 / ambient_CO2)))
```

```{r}
log_response_per_experiment
```

```{r}
knitr::kable(log_response_per_experiment)
```




#ReportExercise_3.5_Aufgabe_3
#Filter the data to create three subsets based on early, mid and late years
```{r}
log_response_ratio_per_phase <- log_response_data |>
  dplyr::filter(Time_.years. <= 3) |>
    dplyr::mutate(Time_.years. = "early_phase")|>
    dplyr::bind_rows(
      log_response_data |>
       dplyr::filter(Time_.years. > 3 & Time_.years. < 6)|>
        dplyr::mutate(Time_.years. = "mid_phase")|>
       dplyr::bind_rows(
          log_response_data |>
           dplyr::filter(Time_.years. >= 6) |>
            dplyr::mutate(Time_.years. = "late_phase")))
```

```{r}
log_response_ratio_per_phase
```

```{r}
knitr::kable(log_response_ratio_per_phase)
```






